In [6]:
# Import libraries 
import numpy as np 
import pandas as pd 
# Import label encoder 
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report


from sklearn.model_selection import train_test_split



import pickle

from sklearn.model_selection import train_test_split # Import train_test_split function

# Import dataset 
df = pd.read_csv('Processed_data15.csv')  

In [7]:
df.head(90)

year  month  day carrier origin dest  delayed
0   2013      1    1      UA    EWR  IAH        0
1   2013      1    1      UA    LGA  IAH        1
2   2013      1    1      AA    JFK  MIA        1
3   2013      1    1      B6    JFK  BQN        0
4   2013      1    1      DL    LGA  ATL        0
..   ...    ...  ...     ...    ...  ...      ...
85  2013      1    1      UA    EWR  MCO        1
86  2013      1    1      B6    JFK  SYR        0
87  2013      1    1      B6    JFK  SFO        0
88  2013      1    1      AA    LGA  ORD        0
89  2013      1    1      UA    EWR  IAH        1

[90 rows x 7 columns]

In [8]:
columns= ['carrier','dest', 'origin']
le=LabelEncoder()
for i in columns:
     df[i]=le.fit_transform(df[i])

In [9]:
df['carrier'].unique()

array([11,  1,  3,  4,  5,  9, 12, 14, 13,  7,  2,  0,  6,  8, 15, 10])

In [10]:
df['origin'].unique()

array([0, 2, 1])

In [11]:
df['dest'].unique()

array([ 43,  57,  12,   4,  68,  35,  42,  53,  70,  99,  49,  89,  30,
        11,  48,  60,  32,  82,  91,  73,  16,  23,  14,  29,  94,  61,
        92, 103,  58,  88,  81,  98,  95,  79,  24,  47,  21,  55,  74,
        83,  28,  22,  96,  64,  46,  54,  40,  10,   5,  13,  72,  97,
        33,   6,  78,  45,  85,  19,  41,  51,  27,   2,   7,  56,  59,
        37,  26,  15,  80,  38,  36,  52,  69,  84,  87,  71,  90,  67,
        25,  65,  93, 102,  77,  31,  75, 100,   9,  66,  18,  39,  17,
        62,  34,  76,   1,   8,   0,  44,  63,  86,  50,  20, 101,   3])

In [12]:
df.head(90)

year  month  day  carrier  origin  dest  delayed
0   2013      1    1       11       0    43        0
1   2013      1    1       11       2    43        1
2   2013      1    1        1       1    57        1
3   2013      1    1        3       1    12        0
4   2013      1    1        4       2     4        0
..   ...    ...  ...      ...     ...   ...      ...
85  2013      1    1       11       0    53        1
86  2013      1    1        3       1    98        0
87  2013      1    1        3       1    89        0
88  2013      1    1        1       2    68        0
89  2013      1    1       11       0    43        1

[90 rows x 7 columns]

In [13]:
X = df.iloc[:, 0:6].values # from column(years) to column(distance)
X[0:5]

array([[2013,    1,    1,   11,    0,   43],
       [2013,    1,    1,   11,    2,   43],
       [2013,    1,    1,    1,    1,   57],
       [2013,    1,    1,    3,    1,   12],
       [2013,    1,    1,    4,    2,    4]], dtype=int64)

In [14]:
y = df['delayed']
y.head().to_frame()

delayed
0        0
1        1
2        1
3        0
4        0

In [15]:
for i in range(0, 20):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=i)
    
    #creating random forest classifier
    clf = RandomForestClassifier(random_state=i)
    clf.fit(X_train, y_train)
    
    #determining the score
    train_score = clf.score(X_train, y_train)
    test_score = clf.score(X_test, y_test)
    print("Test: {}, Train: {} and Random State: {}".format(test_score, train_score, i))

Test: 0.7034715348803109, Train: 0.8358756705456827 and Random State: 0
Test: 0.7038258978212789, Train: 0.8354561339910146 and Random State: 1
Test: 0.7033493407627357, Train: 0.8359937924882591 and Random State: 2
Test: 0.7037159231154613, Train: 0.8358267925004786 and Random State: 3
Test: 0.7031293913511003, Train: 0.8361852314986415 and Random State: 4
Test: 0.7010520913523223, Train: 0.8363440851455547 and Random State: 5
Test: 0.7049500837029705, Train: 0.8357697681144072 and Random State: 6
Test: 0.7026894925278298, Train: 0.835908255909152 and Random State: 7
Test: 0.7031416107628579, Train: 0.8356720120239991 and Random State: 8
Test: 0.703569290174371, Train: 0.8359652802952234 and Random State: 9
Test: 0.7020296442929237, Train: 0.8364703534289986 and Random State: 10
Test: 0.7049256448794555, Train: 0.8356190608083615 and Random State: 11
Test: 0.7041924801740044, Train: 0.8353217193667034 and Random State: 12
Test: 0.7022373742928015, Train: 0.8356353534900961 and Random 

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=18)
clf = RandomForestClassifier(random_state=18)
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=18)

In [17]:
print("Train set: ", clf.score(X_train, y_train))

Train set:  0.8363318656342538


In [18]:
print("Test set: ", clf.score(X_test, y_test))

Test set:  0.7019318889988636


In [19]:
#Create a Random Forest Classifier
clf = RandomForestClassifier(random_state=18)
clf.fit(X_train, y_train)

# Saving model to disk
pickle.dump(clf,open('model.pkl','wb'))

model = pickle.load(open('model.pkl','rb'))

In [20]:
# predicting the trained Classifier to the test
yhat = clf.predict(X_test)

In [21]:
# Viewing the predicted probabilities of first 10 observations
yhat_prob = clf.predict_proba(X_test)[:10]

In [22]:
print(classification_report(y_test, yhat))

              precision    recall  f1-score   support

           0       0.77      0.84      0.80     58830
           1       0.46      0.35      0.40     23007

    accuracy                           0.70     81837
   macro avg       0.61      0.60      0.60     81837
weighted avg       0.68      0.70      0.69     81837

